### ISSUE TITLE
[FEAT] RestDocsHelper 클래스를 구현한다.

### ISSUE THREAD

**Issue by hyuunnn** [KEEPER31337/Homepage-Back-R2#117]
## 📝 Description

https://github.com/KEEPER31337/Homepage-Back-R2/pull/115#issuecomment-1435498093 

Spring Rest Docs를 작성하다 보니 방대한 기능들을 static import하여 사용하고 있었고, 사용해보면 코드가 더러워지는 것을 느낄 수 있습니다.

반복적으로 사용되는 패턴들을 메서드화하고, 별도의 Helper 클래스를 만들어서 사용하면 좋겠다는 생각이 들었습니다.

### 관련 글

<a href="https://johngrib.github.io/wiki/restdoc-item-generator/">짜증나는 Restdoc 템플릿을 조금 더 편하게 작성하자</a>

<a href="https://github.com/thefarmersfront/spring-rest-docs-guide">spring-rest-docs-guide</a> - Enum 값을 docs에 넣기 위한 `generateEnumListFormatAttribute` 메서드를 만들어서 사용하고 있다.

<a href="https://techblog.woowahan.com/2597/">Spring Rest Docs 적용</a>

<a href="https://backtony.github.io/spring/2021-10-15-spring-test-3/">Spring REST Docs 적용 및 최적화 하기</a>, <a href="https://techblog.woowahan.com/2678/">Spring REST Docs에 날개를… (feat: Popup)</a> - Enum을 별도의 팝업 창으로 분리한 방법을 사용하는데 신박했다.

<a href="https://helloworld.kurly.com/blog/spring-rest-docs-guide/">내가 만든 API를 널리 알리기 - Spring REST Docs 가이드편</a>

<a href="https://velog.io/@dae-hwa?tag=Spring">dae-hwa님 velog</a>

## ☑️ TODO

- [ ] RestDocsHelper 클래스를 구현한다.

**Comment by gusah009** [comment]
응원합니다

**Comment by 02ggang9** [comment]
해당 기능은 편의성 제공을 위한 이슈라서 close 하도록 하겠습니다.
