### ISSUE TITLE
[REFACTOR] Redis Sorted set을 사용하여 랭킹 기능을 구현한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#258]
## 📝 Description

- Redis Sorted set 조사하기
- 홈페이지 출석 & CTF 랭킹 기능

**Comment by gusah009** [comment]
sorted set으로 redis에서 출석 랭킹 정보를 모두 가지고 있으려면 랭킹별 entity를 redis가 가지고 있어야 하는데, 이건 출석 repository에 redis cache를 다는 작업과 같으므로 

1. 랭킹 조회 트래픽이 많거나
2. 랭킹 조회 시 api 쿼리 시간이 오래 걸리거나

한다면 mysql 접근 전에 캐시를 다는게 맞음. 그런데 지금은 명확한 근거가 없으므로 이 이슈는 close 하겠습니다.

@02ggang9

**Comment by 02ggang9** [comment]
감사합니다~~
