### ISSUE TITLE
[REFACTOR] 하드 코딩된 테스트 코드를 수정한다.

### ISSUE THREAD

**Issue by 02ggang9** [KEEPER31337/Homepage-Back-R2#398]
## 📝 Description

KEEPER R2 ReadME 부분에 Quick Start를 위한 코드를 작성하다가 테스트 코드 깨짐 현상을 발견했습니다. (Quick Start는 쉘 코드 실행만으로 KEEPER 홈페이지가 띄워질 수 있도록 만드는 인프라 코드입니다. 한상곤 교수님의 ReadME 작성법 수업에서 나온 내용을 적용하고자 합니다. 완성되면 검수 받도록 하겠습니다!)

![image](https://github.com/KEEPER31337/Homepage-Back-R2/assets/105693150/86d6e98b-fda3-4571-bb82-bf96b07c57a3)

테스트가 깨지는 코드의 accessToken은 실제 운영에서 사용하고 있는 SECRET key 값을 기반으로 만든 accessToken 입니다. Quick Start에 들어간 SECRET 값은 "1111...11"로 의미 없는 값을 넣어줬는데 이렇게 된다면 테스트 코드에서 기대하는 ExpiredJwtException 예외가 잡히지 않고 MALFORMED 또는 WRONG_SIGNATURE 예외가 발생할 것으로 예상이 됩니다.

```
      @Test
      @DisplayName("AT가 만료되었으면 200 OK를 응답한다.")
      void should_200OK_when_accessTokenExpired() throws Exception {
        String expiredToken = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOiJST0xFX-2ajOybkCIsImlhdCI6MTY3NDQ1MjM1NSwiZXhwIjoxNjc0NDUyMzU1fQ.FoRbgOGlzLwizp9jQNmM6pET4zA8TPXa56zZlsl6Al8";
        Cookie expiredCookie = new Cookie(ACCESS_TOKEN.getTokenName(), expiredToken);
        expiredCookie.setHttpOnly(true);
        assertThatThrownBy(() -> jwtTokenProvider.getAuthId(expiredToken))
            .isInstanceOf(ExpiredJwtException.class);
      }
```

## ☑️ TODO

- [x] 동적으로 accessToken을 생성하도록 수정

**Comment by shkisme** [comment]
요건 해결 된건가용?

**Comment by 02ggang9** [comment]
머지됐습니다~
