### ISSUE TITLE
[DOCS] 전반적인 로그인 로직 이해 및 문서 작성

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#410]
## 📝 Description

전반적인 로그인 로직을 이해하고, 개선하고 싶은 점이 있다면 개선한다.

## ☑️ TODO

- [ ] 로그인 로직 이해
- [ ] 이해한 것을 바탕으로 인수인계 문서 작성

**Comment by 02ggang9** [comment]
KEEPER & BDD 홈페이지 개발 협력 프로젝트가 중지되었기 때문에 close 하도록 하겠습니다. 수고하셨습니다!
