### ISSUE TITLE
[FEAT] PR에 CI를 도입한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#422]
## 💬 기능 설명

Github Actions 를 사용한 CI 환경을 구축해봅니다.

Pull Request 를 올렸을 때 자동으로 빌드 및 테스트를 수행하여 문제가 없는 코드인지 검사합니다.

## ☑️ TODO

- [ ] Github Actions 를 사용한 PR CI 환경 구축

**Comment by 02ggang9** [comment]
머지됐으므로 close 하겠습니다~
