### ISSUE TITLE
[FEAT] 캘린더 도메인에 필요한 API를 개발한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#424]
## 💬 기능 설명

캘린더 도메인에 필요한 API를 개발한다.

## ☑️ TODO

API 설계 부탁드립니다.

- [ ] todo1

**Comment by 02ggang9** [comment]
캘린더 개발은 중지 되었으므로 close 하도록 하겠습니다
