### ISSUE TITLE
Thumbnail Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#6]
## 📝 Description

Thumbnail Entity, Repository를 생성한다.

## ☑️ TODO

- [ ] Thumbnail Entity를 생성한다.
- [ ] Thumbnail Repository를 생성한다.

**Comment by gusah009** [comment]
@xet-a 썸네일 엔티티 및 레포지토리는 https://github.com/KEEPER31337/Homepage-Back-R2/issues/25 이슈에서 제가 개발하겠습니다!
