### ISSUE TITLE
File Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#7]
## 📝 Description

File Entity, Repository를 생성합니다.

## ☑️ TODO

- [ ] File Entity를 생성한다.
- [ ] File Repository를 생성한다.

**Comment by gusah009** [comment]
@xet-a 파일 엔티티 및 레포지토리는 https://github.com/KEEPER31337/Homepage-Back-R2/issues/25 이슈에서 제가 개발하겠습니다!
