### ISSUE TITLE
[FEAT] TestHelper 클래스 작성에 도움을 주는 인터페이스를 구현한다.

### ISSUE THREAD

**Issue by hyuunnn** [KEEPER31337/Homepage-Back-R2#75]
## 📝 Description

TestHelper 클래스를 만들어보고, 이미 만들어진 코드들을 보니 `generate()`, `builder()`라는 이름의 중복되는 메서드가 각 클래스마다 구현되어 있습니다.

```java
// AttendanceTestHelper.java
public Attendance generate() {
  return this.builder().build();
}

public AttendanceBuilder builder() {
  return new AttendanceBuilder();
}

// MemberTestHelper.java
public Member generate() {
  return this.builder().build();
}

public MemberBuilder builder() {
  return new MemberBuilder();
}

// SeminarTestHelper.java
public Seminar generate() {
  return this.builder().build();
}

public SeminarBuilder builder() {
  return new SeminarBuilder();
}
```

`generate()` 메서드가 하는 역할은 동일하며, `builder()` 메서드는 내부에 구현된 builder 클래스를 생성하여 반환해주는 역할을 하고 있습니다.

이를 인터페이스로 만들어서 통일하면 좋겠다는 생각이 들었습니다..!
제네릭과 디폴트 메서드를 활용하면 될 것 같습니다.

#### 장점

```java
// SeminarAttendanceRepositoryTest.java
seminar = seminarTestHelper.generate();
member = memberTestHelper.generate();
statusType = ATTENDANCE;
seminarAttendance = seminarAttendanceRepository.save(SeminarAttendance.builder()
    .seminar(seminar)
    .member(member)
    .seminarAttendanceStatus(initAttendanceStatus(statusType))
    .build());
```
위 코드는 `SeminarAttendanceRepositoryTest`에서 작성한 코드 중 일부인데, 세미나 참여를 하기 전에 필요한 세미나 생성(`seminarTestHelper.generate()`)과 멤버 정보(`memberTestHelper.generate()`)를 깔끔하게 만들 수 있습니다.

## ☑️ TODO

- [ ] `TestHelper` 개발에 도움을 주는 인터페이스를 구현한다.

**Comment by gusah009** [comment]
@02ggang9 `generate()`만 인터페이스로 빼는건 크게 의미가 없어 close합니다. 추후에 `Builder`까지 `reflection`으로 값을 넣어줄 수 있으면 도전해볼만 할 것 같습니다.

reflection으로 빌더를 재구조화 하는건 이 이슈를 벗어나므로 일단 close하겠습니다.

**Comment by 02ggang9** [comment]
수고하셨습니다~ 감사합니다!
